version: '3.3'

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8000:8000
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
 
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      args:
      - VUE_APP_TITLE=Docker Application
      - VUE_APP_API_BACKEND=http:\\localhost:8000
    ports:
      - 8080:80
    