version: '3.3'

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
 
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 8080:80
