apiVersion: v1
kind: ConfigMap
metadata:
  name: okteto-frontend-configmap
data:
  config.js: |
    var config = (() => {
    return {
        "VUE_APP_TITLE":"kubenates run",
        "VUE_APP_API_BACKEND":"https://fastapi-service-rushabh2390.cloud.okteto.net"
      };
    })();