apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: rdddocker/backend
        imagePullPolicy: Never
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
   name: fastapi-service
   labels:
     app: fastapi-service
spec:
   type: LoadBalancer
   ports:
     - protocol: TCP
       port: 8000
       targetPort: 8000
   selector:
     app: backend