apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fastapi
  name: fastapi-deployment
spec:
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: rdddocker/backend
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
   name: fastapi-service
   labels:
     app: fastapi-service
spec:
   type: LoadBalancer
   ports:
     - protocol: TCP
       port: 8000
       targetPort: 8000
   selector:
     app: fastapi