name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Frontend Docker image
      run: cd frontend && docker build . --file Dockerfile --tag  rdddocker/summary_frontend:latest
      
    - name: Build the Backend Docker image
      run: cd backend && docker build . --file Dockerfile --tag  rdddocker/summary_backend:latest
